### ISSUE TITLE
Failed to run workflow_demo.py

### ISSUE THREAD

**Issue by hanzengbo** [facebookincubator/profilo#38] opened 2018-12-16 07:46 UTC
Hi,
   I run the sample.apk on Pixel 2 which system is Android P, and get the trace log: [override-2018-12-16T12-51-43-E49izqDgqh8.zip.log](https://github.com/facebookincubator/profilo/files/2683354/override-2018-12-16T12-51-43-E49izqDgqh8.zip.log)
](url)
  But  when running the analysis command, I got the error message:
![image](https://user-images.githubusercontent.com/6788832/50051247-8a893900-0149-11e9-8d23-ff22b1a1c3a4.png)
  I tried to run the gunzip command, and got information:
  
![image](https://user-images.githubusercontent.com/6788832/50051255-a8ef3480-0149-11e9-8d9c-f2a2cc1da0cb.png)
  Could you tell me how to fix it, Thanks.

**Comment by ricardorey10** [comment] 2018-12-17 22:34
Hey,

The problem is that the file is actually a `zip` file with the expected `gzip` file within. I already wrote a fix for this, which I'll publish as soon as I can =)

**Comment by hanzengbo** [comment] 2018-12-18 04:14
Thanks， look forward to your submit.

**Comment by ricardorey10** [comment] 2018-12-19 18:03
Hey, I just landed 261c44dc0a72d854474a685a7ca5c2562f1ce6fb, which should take care of this issue. Please let me know if you run into any other problems =)

**Closed by ricardorey10** 2018-12-19 18:03 UTC

**Comment by popahqiu** [comment] 2018-12-25 07:58
Hi, just feeding back.
Commit [](url)https://github.com/facebookincubator/profilo/commit/261c44dc0a72d854474a685a7ca5c2562f1ce6fb works great. 👍 
Thanks a lot. :-)
