### ISSUE TITLE
Can't pull trace from Samsung J5 (Android 5.1.1)

### ISSUE THREAD

**Issue by deadmoto** [facebookincubator/profilo#35] opened 2018-09-20 23:02 UTC
When I run `python3 -m profilo.profilo pull_last_trace com.facebook.profilo.sample`, I get the following error:
```
File /data/data/com.facebook.profilo.sample/Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SM-J500H_5.1.1_0045 was moved. Retrying...
```
Same happens with my application when I integrate Profilo into the app.

**Comment by ricardorey10** [comment] 2018-09-21 15:45
Uhh, that's a pretty weird error :/ 

Can you try looking for the traces with `adb`? Run

```
adb shell run-as com.facebook.profilo.sample ls cache/upload
```

And see if there's something in there. If there is, as a workaround you can get the traces using

```
adb exec-out run-as com.facebook.profilo.sample cat cache/upload/trace_name > foo
```

Also, is there any chance you could try this in an emulator using the same Android version, just a different device (say, Nexus or something like that)? I have had issues in the past with Samsung devices, so I would like to see if the problem is directly with the device.

**Comment by ricardorey10** [comment] 2018-09-21 18:36
@deadmoto 

Looks like the trace is actually there! =D See that `override-main-4717-2018-9-21T7-1-21-El4j7o7Hqno-cs-cac74009.log` file? That's the trace that was generated. Let's try this:

```
adb exec-out run-as com.facebook.profilo.sample cat cache/upload/override-main-4717-2018-9-21T7-1-21-El4j7o7Hqno-cs-cac74009.log > foo
```

If that works, `foo` will be the trace. You can then process it with the `workflow_demo.py` script, doing something like `python3 -m profilo.workflow_demo foo blocks` =)

Please let me know if this works.

**Comment by deadmoto** [comment] 2018-09-21 19:19
Here's what I got on Android 5.1.1 emulator:
```
deadmoto$ sh workflow_demo.sh 
File /data/data/com.facebook.profilo.sample/run-as: exec failed for find Error:Permission denied was moved. Retrying...
```
I pulled down the log file as you suggested, but `workflow_demo` script cannot process it because some error messages creeped into it's head:
```
Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SM-J500H_5.1.1_0045
[DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
```

**Comment by ricardorey10** [comment] 2018-09-21 20:16
Mhm, this is weird. Are you doing this in your computer? The `workflow_demo` shouldn't have any `run-as`, as it is only working with files on your local file system (i.e., the step of downloading a trace from the device and into your own computer should be done prior to running the `workflow_demo`).

Can you run `gunzip -c` on the file you pulled and paste the output here? You might have to unzip it first.

**Comment by deadmoto** [comment] 2018-09-21 20:20
Here is the output:
```
deadmoto$ gunzip -c override-main-4717-2018-9-21T7-1-21-El4j7o7Hqno-cs-cac74009.log 
gunzip: override-main-4717-2018-9-21T7-1-21-El4j7o7Hqno-cs-cac74009.log: not in gzip format
```

**Comment by ricardorey10** [comment] 2018-09-21 20:33
This is getting super hacky, but I found a way to make it work (~ish). First, remove the first 2 lines, which seem to be garbage from that "selinux" error creeping into the file you pulled:

```
 1 Function: selinux_compare_spd_ram , priority [2] , priority version is VE=SEPF_SM-J500H_5.1.1_0045
 2 [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
```

Now the gunzip command should work. Kinda. There seems to be trailing garbage, but it looks like it's correctly ignored:

```
$> gunzip -c override-main-4717-2018-9-21T7-1-21-El4j7o7Hqno-cs-cac74009.log > foo
gunzip: override-main-4717-2018-9-21T7-1-21-El4j7o7Hqno-cs-cac74009.log: trailing garbage ignored
```

Here's how that `foo` file looks like:

```
$> head -n 20 foo
dt
ver|3
id|El4j7o7Hqno
prec|6
pid|4717
arch|armv7l
os|Android5.1.1

1|TRACE_START|2907740045|4717|2147483647|1|5294139391992572392
1|MARK_PUSH|64341|17|-2147483647|-1|-5294139391992572392
3|STRING_NAME|2|waitForTask
2|MARK_POP|60|0|0|0|0
1|MARK_PUSH|25|0|0|0|0
6|STRING_NAME|5|waitForTask
2|MARK_POP|10|0|0|0|0
1|MARK_PUSH|46|0|0|0|0
9|STRING_NAME|8|eglSwapBuffers
2|MARK_PUSH|313|0|0|0|0
11|STRING_NAME|10|setBuffersTransform
2|MARK_POP|32|0|0|0|0
```

Now you're almost ready to process it with the `workflow_demo` script. But first you need to `gzip` it. So run `gzip foo`, and now you can do:

```
$> python -m profilo.workflow_demo foo.gz blocks
,IsMain,tid,event,mean,median,std
0,True,4717,performTraversals,1987764.1791044776,1584000.0,1058149.3227161395
1,True,4717,draw,1835244.776119403,1458000.0,1016239.2507237245
2,True,4717,Record View#draw(),935301.4925373135,859000.0,316723.30100697896
3,True,4717,Full suspend check to Missing,6724000.0,6724000.0,0.0
4,False,4734,waitForTask,19967.183770883054,11000.0,52720.84584469025
5,False,4734,eglSwapBuffers,732068.6567164179,590000.0,770320.1300426609
...
```

Please let me know if this works (fingers crossed!). I'll also dig around about those SELinux errors you're seeing, because I had never seen anything like that :/

**Comment by deadmoto** [comment] 2018-09-21 21:00
Nay, still getting `gunzip: data stream error` after removing the first two lines.
I tried to edit the log file with Android Studio and `nano`.
What was your tool that made it a valid gzip archive?

**Comment by ricardorey10** [comment] 2018-09-24 15:37
@deadmoto were you able to make this work?

**Comment by deadmoto** [comment] 2018-09-24 16:57
@ricardorey10 after trying different utilities I figured out that only `vim` cuts the lines properly.
Anyways, thanks for your help!
Feel free to use me as a Guinea pig to verify a fix for this when it comes out.

**Comment by ricardorey10** [comment] 2018-09-24 17:01
Will do! Thanks!

In the meantime, I will close this task so that it doesn't pollute our queue =) 

Ping us any time you need help!

**Closed by ricardorey10** 2018-09-24 17:01 UTC
